"""MCare domain models — Pydantic schemas for agent routing and clinical card output.

Models:
- SpecialistType: enum for agent personas (triage|coverage|network|general)
- ClinCard: structured output from agents (symptoms, hypotheses, next steps)
- TransmitLog: audit trail for escalations to Lisacare (who/when/why)
- MCareResponse: API response envelope (message + clin_card + metadata)
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class SpecialistType(str, Enum):
    """Agent specialist personas."""

    TRIAGE = "triage"  # Acute symptoms, emergency routing
    COVERAGE = "coverage"  # Insurance benefits, guardrails
    NETWORK = "network"  # Clinic access, geography
    GENERAL = "general"  # FAQ, administrative


class ClinCard(BaseModel):
    """Structured clinical orientation card generated by MCare agents.

    Output format for triage responses:
    - symptoms: [str] — collected symptoms from user
    - hypothesis_list: [str] — possible conditions (non-diagnostic, hypothesis only)
    - next_steps: str — recommended action (when to see doctor, which clinic, etc)
    - red_flags: [str] — critical flags (difficulty breathing, etc) → urgent clinic
    - tags: [str] — always includes "IA" + "Hypothèses non validées"
    - concern_level: str — "bas" | "modere" | "haut" | "critique"

    Example:
    ```json
    {
        "symptoms": ["Fièvre 38.5°C", "Toux sèche depuis 2 jours"],
        "hypothesis_list": [
            "Syndrome grippal possible",
            "Infection virale des voies respiratoires"
        ],
        "next_steps": "Consulter un médecin si fièvre persiste >3 jours",
        "red_flags": [],
        "tags": ["IA", "Hypothèses non validées"],
        "concern_level": "modere"
    }
    ```
    """

    symptoms: list[str] = Field(
        default_factory=list,
        description="Collected symptoms from user conversation",
    )
    hypothesis_list: list[str] = Field(
        default_factory=list,
        description="Possible conditions (never diagnostic) - for doctor exploration",
    )
    next_steps: str = Field(
        default="",
        description="Recommended action: see doctor, go to clinic, when to escalate",
    )
    red_flags: list[str] = Field(
        default_factory=list,
        description="Critical flags requiring immediate clinic visit",
    )
    tags: list[str] = Field(
        default_factory=lambda: ["IA", "Hypothèses non validées"],
        description="Always includes IA tag + non-diagnostic disclaimer",
    )
    concern_level: str = Field(
        default="modere",
        description="Urgency level: bas|modere|haut|critique",
        pattern="^(bas|modere|haut|critique)$",
    )


class TransmitLog(BaseModel):
    """Audit trail for escalation to Lisacare (human doctor review)."""

    id: str = Field(..., description="Unique transmit log ID (UUID)")
    conversation_id: str = Field(..., description="MCare conversation ID")
    cssa_id: str = Field(..., description="Member CSSA ID")
    beneficiary_name: str | None = Field(
        default=None, description="Beneficiary name if dependent"
    )
    transmitted_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Timestamp of transmission to Lisacare",
    )
    transmitted_by: str = Field(
        default="system", description="User ID or 'system' (agent auto-escalation)"
    )
    reason: str = Field(
        default="",
        description="Why transmitted: 'red_flags' | 'user_request' | 'quality_check'",
    )
    lisacare_id: str | None = Field(
        default=None, description="Lisacare case ID if transmission succeeded"
    )
    lisacare_status: str = Field(
        default="pending_doctor_review",
        description="Status from Lisacare: pending_doctor_review|assigned|completed",
    )


class MCareResponse(BaseModel):
    """API response envelope for MCare agent chat."""

    conversation_id: str = Field(..., description="Conversation ID")
    cssa_id: str = Field(..., description="Member CSSA ID (upper case)")
    message: str = Field(..., description="Agent's response text")
    message_type: str = Field(
        default="text", description="text | clin_card"
    )
    clin_card: ClinCard | None = Field(
        default=None, description="Structured clinical card if triage response"
    )
    specialist_type: str = Field(
        default="general", description="Agent type: triage|coverage|network|general"
    )
    tags: list[str] = Field(
        default_factory=lambda: ["IA", "Hypothèses non validées"],
        description="Response tags",
    )
    quota_remaining: int | None = Field(
        default=None, description="Member's remaining MCare credits"
    )
    safety_check: dict | None = Field(
        default=None, description="Safety evaluation result"
    )


class MCareErrorResponse(BaseModel):
    """Error response for MCare API."""

    error: str = Field(..., description="Error message")
    detail: str | None = Field(
        default=None, description="Additional details"
    )
    request_id: str | None = Field(
        default=None, description="Request ID for debugging"
    )


class QuotaCheckResponse(BaseModel):
    """Response from quota check endpoint."""

    cssa_id: str = Field(..., description="Member CSSA ID")
    quota_remaining: int = Field(..., description="Remaining MCare credits")
    status: str = Field(..., description="ACTIVE | EXHAUSTED | INACTIVE")
    message: str | None = Field(default=None, description="Human-readable message")


class CoverageInfoResponse(BaseModel):
    """Response from coverage lookup endpoint."""

    plan_name: str = Field(..., description="Plan name (silver|gold|platinum)")
    ceiling_amount: float = Field(..., description="Global yearly ceiling (XOF)")
    ceiling_label: str = Field(..., description="Human-readable ceiling (e.g., '500,000 XOF')")
    franchises: dict[str, float] = Field(
        default_factory=dict, description="Per-act franchises"
    )
    carencies: dict[str, int] = Field(
        default_factory=dict, description="Waiting periods in days"
    )
    excluded_acts: list[str] = Field(
        default_factory=list, description="Non-covered acts"
    )
